name: CICDJAVA

on:  
  push:  
  pull_request:  
    types:  [ opened, closed ]

  release:
    types: [ created ]

env:
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo github.release.target_commitish:${{ github.release.target_commitish }} github.event_name:${{ github.event_name }} - github.base_ref:${{ github.base_ref }} - github.ref:${{ github.ref }} - github.event.pull_request.merged:${{ github.event.pull_request.merged }} - github.event.action:${{ github.event.action }} $GITHUB_CONTEXT - Compile Step..
    
  DeployDev:
    name: Deploy to Dev 
    if: github.event_name == 'pull_request' && github.ref == 'develop' && github.event.pull_request.merged
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'http://someweb.com'
    steps:
      - name: Deploy
        run: echo Deploying Dev....   
    
  DeployPreproduction:
    name: Deploy to Preproduction 
    needs: [DeployDev]
    if: github.event_name == 'pull_request' && github.ref == 'staging' && github.event.pull_request.merged
    runs-on: ubuntu-latest
    environment: 
      name: Preproduction
      url: 'http://someweb.com'
    steps:
      - name: Deploy
        run: echo I am deploying!!!
            
  DeployProduction:
    name: Deploy to Production 
    if: github.event_name == 'release'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://someweb.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
