name: Deploy to Staging (Master)
on:
  push:
    branches:
      - master
    tags:
      - '!refs/tags/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v1              
      - name: Deploy to Staging
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
        run: |
          deploymentTag=$(date +'v%Y.%m.%d.%H%M')
          git tag -a $deploymentTag -m "This is an automatic message. Deployment done to staging with id: $deploymentTag" 
          git.exe push --tags --progress "origin" master:master
          echo "Foobar :: [$foobar]"
