name: Deploy to Staging (Master)
on:
  push:
    branches:
      - master
    tags:
      - '!refs/tags/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2 
          
      - name: Deploy to Staging          
        run: |
          deploymentTag=$(date +'v%Y.%m.%d.%H%M')
          echo "$deploymentTag"   
          git config --global user.email "generic_action@github.com"
          git config --global user.name "generic_action"
          git checkout -f -B staging remotes/origin/staging --
          git tag -a $deploymentTag -m "Deployment done to staging with id: $deploymentTag" 
          git push --tags --progress "origin" staging:staging
