name: Deploy to Staging (Master)
on:
  push:
    branches:
      - master
    tags:
      - '!refs/tags/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2 
        with:          
          token: ${{ secrets.GitHub_PAT }}
          
      - name: Deploy to Staging          
        run: |
          deploymentTag=$(date +'v%Y.%m.%d.%H%M')
          echo "$deploymentTag"
          git checkout -f master --
          git tag -a $deploymentTag -m "This is an automatic message. Deployment done to staging with id: $deploymentTag" 
          git push --tags --progress "origin" master:master
