name: Tagging to Staging Branch
on:
  push:
    branches:
      - staging
env:
  GITHUB_CONTEXT: ${{ toJson(github) }}
  PUSHER_EMAIL: ${{ github.event.pusher.email }}
  PUSHER_NAME: ${{ github.event.pusher.name }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2           
      - name: Tagging to Staging Branch        
        run: |
          deploymentTag=$(date +'v%Y.%m.%d.%H%M')
          echo "$deploymentTag"       
          echo "PUSHER_EMAIL: $PUSHER_EMAIL"
          echo "PUSHER_NAME: $PUSHER_NAME"
          git config --global user.email  "$PUSHER_EMAIL"
          git config --global user.name "$PUSHER_NAME"
          git fetch
          git checkout -f --track -B staging remotes/origin/staging --
          git pull --progress -v --no-rebase --no-ff "origin"
          git tag -a $deploymentTag -m "Deployment done to staging with id: $deploymentTag" 
          echo "Tag creado: $deploymentTag"  
          git push --tags --progress "origin" staging:staging
          echo "Push creado con el tag: $deploymentTag"  
          echo "$GITHUB_CONTEXT"
