name: Tagging to Staging Branch
on:
  push:
    branches:
      - staging
env:
  GITHUB_CONTEXT: ${{ toJson(github) }}
  PUSHER_EMAIL: ${{ github.event.pusher.email }}
  PUSHER_NAME: ${{ github.event.pusher.name }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2    
        with:
          ref: 'staging'
      - name: Tagging to Staging Branch        
        run: |
            deploymentTag=$(date +'v%Y.%m.%d.%H%M')
            echo "Tag Id: $deploymentTag"
            messageTag="Tag $deploymentTag created automatically due to the merge request to staging branch with details: Commit hash: ${{ github.sha }} Username: ${{ github.event.pusher.name }} Email: ${{ github.event.pusher.email }}."
            echo "Message Tag: $messageTag"            
            echo ""
            git config --global user.email "${{ github.event.pusher.email }}"
            git config --global user.name "${{ github.event.pusher.name }}"
            git tag -a $deploymentTag -m "$messageTag"
            echo ""
            echo "Tag created: $deploymentTag into staging branch."
            echo ""
            git push --tags --progress
            echo "Push created with tag: $deploymentTag"
            echo "$GITHUB_CONTEXT"
