name: Tagging to Staging Branch
on:
  push:
    branches:
      - staging
env:
  GITHUB_CONTEXT: ${{ toJson(github) }}
  EMAIL: ${{ toJson(github).event.pusher.email }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2           
      - name: Tagging to Staging Branch        
        run: |
          deploymentTag=$(date +'v%Y.%m.%d.%H%M')
          echo "$deploymentTag"   
          echo "$ {{ github.event.pusher.email }}"
          echo "$ {{ github.event.pusher.name }}"
          echo "$GITHUB_CONTEXT"
          echo "$EMAIL"
          git config --global user.email  "generic_action@github.com"
          git config --global user.name "generic_action"
          git fetch
          git checkout -f --track -B staging remotes/origin/staging --
          git pull --progress -v --no-rebase --no-ff "origin"
          git tag -a $deploymentTag -m "Deployment done to staging with id: $deploymentTag" 
          echo "Tag creado: $deploymentTag"  
          git push --tags --progress "origin" staging:staging
          echo "Push creado con el tag: $deploymentTag"  
